{% set version = "10.4.2" %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 3a7e027af8c8e91c196ac259c703d78cd55c364706ddafbc66d02c326e57a456
  patches:
    - 0001-Disable-jemalloc-on-linux.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
    - dbast
