{% set version = "10.2.0" %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 73329fe24c53f0ca47cd0939256ca5c4644742cb7c14cf4114c8c9871336d342
  patches:
    - 0001-Disable-jemalloc-on-linux.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
