{% set version = "8.3.1" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 834a90fbb4e1deee2ca7f3aa84575c9187869d8af00f72e431ecab4776ae1f62

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
