{% set version = "8.4.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: d0c2fc7ddbe74e3fd88bf5bb02e0f69078ee6d2aeea3d8df42f508543c9db05d
  #patches:
  #  - 0001-Disable-jemalloc-on-linux.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
