{% set version = "8.3.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 3c5a8a03c4f6ade73b92432ed0ba51591db19b0d136073fa3ccfa99d63403d52

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}   # [unix]
    - {{ native }}binutils    # [win]

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
