{% set version = "10.4.1" %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 59ab83e56743e28eaa92c5497b3998a35744db6d8d574f389456481f2af1cb00
  patches:
    - 0001-Disable-jemalloc-on-linux.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
