travis:
  secure:
    BINSTAR_TOKEN: erIImAuN6QjaXkZ8AzjbrEz5mjRakNVidh7H+55hoLzHebNm4sZ6/WKiw62ytC01g0cCqgQngTwbcSDwzXOBOfxyApLWrHQEyi8ADJNqlX3bTwAfpZACQY84AkS4lMDZ53UibmNceCLQCcSwPQ7ZpfRLMNr4qm7duSM0pKe1DhXSkpU/Rv/sYXTxs/Mi0UThcuBq6362pnEMnT3vZOeZZm/9IyYKeUQa+oMRXjCcTBSJ3bji0BeqFRungrGMmwZ93Y0krJVnnxbBuCfE4/I75PYRh77nfLDluLHvyYbZpoUoktmwXnyf1ldOstFsTBdzsD/FMS3FOl5elaCXHvI1a6SMFvrEvUlXOkS0sdZS++nRwc2GDWUy/EmoJ+2md4m7ZHYc13lnrkfpk5gINnqtJ1xiuhOUuEDH7QyS5qyibSZuUlMetFskAVBcSAFF+Uv+aYvdrnf2HoPYiG6QrW0D14i0OHPCS38GOg4FgI9qKl27uox7GDHUUsS/xuvXlbOnGp3aJTzo64bFtGn0c9KceOACu6tfy7kqh2m0+LUWCB6Bjk14GSQweqIiGVwGtxlD7d/PMR+HhMSfjtg3Pslto3BP6m4uX+y0LrW3jVpHRVwI8Yv1FwIKDNrThrpZFJUlJLn7kOe45q1q2pFK1GIU0u+8VBAnvdv5lzZkIgBvBsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
